# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics
on:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  github-metrics-personal:

    runs-on: ubuntu-latest

    steps:

      - name: 📗 Classic template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # 🙋 Introduction

      - name: 🙋 Introduction (user)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          user: github
          base: header
          plugin_introduction: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_isocalendar: no
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less
          plugin_languages_skipped: lowlighter
          plugin_languages_details: lines, percentage
            #plugin_languages_sections: most-used, recently-used
          plugin_languages_sections: most-used
            #plugin_languages_indepth: yes
          plugin_languages_limit: 6
          plugin_topics: no
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: no
          plugin_notable_repositories: no
          plugin_discussions: no
          config_order: base.header, languages
          output_action: pull-request


      - name: 🦑 Personal metrics (bottom)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: no
          plugin_achievements_display: compact
          config_display: large
          output_action: pull-request-squash

      # ======================================================================================
      # 👨‍💻 Lines of code changed

      - name: 👨‍💻 Lines of code changed
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # 🈷️ Most used languages

      - name: 🈷️ Languages (most used)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_limit: 4
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # ✨ Stargazers over last weeks

      - name: ✨ Stargazers over last weeks
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # 🧮 Repositories traffic

      - name: 🧮 Repositories traffic
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: repositories
          plugin_traffic: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # ♐ Code snippet of the day

      - name: ♐ Code snippet of the day
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

